language: shell

addons:
  homebrew:
    packages:
    update: false

stages:
  - "EDA Tools - Formal"

jobs:
 include:
 # EDA Tools - Formal
  # Linux
  # - stage: "EDA Tools - Formal"
  #   os: linux
  #   env:
  #   - PACKAGE=formal/z3
  # - stage: "EDA Tools - Formal"
  #   os: linux
  #   env:
  #   - PACKAGE=formal/boolector
  # Windows
  - stage: "EDA Tools - Formal"
    os: windows
    env:
    - PACKAGE=formal/z3
  # OSX
  # - stage: "EDA Tools - Formal"
  #   os: osx
  #   osx_image: xcode8.3
  #   env:
  #   - PACKAGE=formal/z3
  # - stage: "EDA Tools - Formal"
  #   os: osx
  #   osx_image: xcode8.3
  #   env:
  #   - PACKAGE=formal/boolector

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
