{% set version = '4.8.7' %}

package:
  name: z3
  version: {{ version }}
  
source:
  folder: z3
  git_url: https://github.com/Z3Prover/z3.git                                         
  git_rev: z3-4.8.7                                                                   

build:
  detect_binary_files_with_prefix: True
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - python 3.7            # [not win]
    - {{ compiler('c') }}   # [not win]
    - {{ compiler('cxx') }} # [not win]
    - make                  # [not win]

about:
  home: https://github.com/Z3Prover/z3/wiki
  license: MIT
  summary: 'Z3 is an efficient SMT solver.'
